esphome:
  name: pee-and-poo-keypad
  friendly_name: Pee and Poo Keypad

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: KEY

ota:
  - platform: esphome
    password: PASS

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Pee-And-Poo-Keypad"
    password: PASS

captive_portal:

# Key order:
# 1 2 3 4
# 5 6 7 8

binary_sensor:

#Key 1
  - platform: gpio
    icon: "mdi:dialpad"
    name: "Pee and Poo Keypad 2x4 Button 1"
    pin:
      number: D4
      inverted: true
      mode: INPUT_PULLUP 


#Key 2
  - platform: gpio
    icon: "mdi:dialpad"
    name: "Pee and Poo Keypad 2x4 Button 2"
    pin:
      number: D3
      inverted: true
      mode: INPUT_PULLUP  

#Key 3
  - platform: gpio
    icon: "mdi:dialpad"
    name: "Pee and Poo Keypad 2x4 Button 3"
    pin:
      number: D2
      inverted: true
      mode: INPUT_PULLUP    

#Key 4
  - platform: gpio
    icon: "mdi:dialpad"
    name: "Pee and Poo Keypad 2x4 Button 4"
    pin:
      number: D1
      inverted: true
      mode: INPUT_PULLUP    

#Key 5
  - platform: gpio
    icon: "mdi:dialpad"
    name: "Pee and Poo Keypad 2x4 Button 5"
    pin:
      number: D5
      inverted: true
      mode: INPUT_PULLUP          

#Key 6
  - platform: gpio
    icon: "mdi:dialpad"
    name: "Pee and Poo Keypad 2x4 Button 6"
    pin:
      number: D6
      inverted: true
      mode: INPUT_PULLUP     

#Key 7
  - platform: gpio
    icon: "mdi:dialpad"
    name: "Pee and Poo Keypad 2x4 Button 7"
    pin:
      number: D7
      inverted: true
      mode: INPUT_PULLUP     

#Key 8
  - platform: gpio
    icon: "mdi:dialpad"
    name: "Pee and Poo Keypad 2x4 Button 8"
    pin:
      number: D8
      inverted: False
      mode: INPUT                 